# -*- coding: utf-8 -*-
__author__ = 'dhernand'

CONST_GPS_3D_CAPTURE_PLUGIN_WINDOW_TITLE = "GPS 3D Capture Plugin"
CONST_GPS_3D_CAPTURE_PLUGIN_COMBOBOX_NO_SELECT_OPTION = " ... "
CONST_GPS_3D_CAPTURE_PLUGIN_GEOIDS_RELATIVE_PATH = "/share/proj"
CONST_GPS_3D_CAPTURE_PLUGIN_GEOIDS_FILTER_1 = "*.gtx"
